Add basic action-based editor, minorly improved from vello_editor.
linebender/parley pull request #126
Opened 2024-10-07 16:09 UTC by xorgy

2024-10-07 16:23 UTC, xorgy commented
This inherits some structural issues from vello_editor in its current state, and with `build_into(...)` it can't be `no_std`

2024-10-07 16:49 UTC, waywardmonkeys reviewed
Didn't review this really, just noticed a couple of nits.

2024-10-07 17:06 UTC, nicoburns requested changes
This generally looks great but I have a few suggestions.

2024-10-07 17:07 UTC, xorgy commented on parley/src/layout/editor.rs
> +    DeleteCurrentSelectionOrToPreviousWordBoundary,
I think I agree.

2024-10-07 17:08 UTC, xorgy commented on parley/src/layout/editor.rs
> +    InsertOrReplaceCurrentSelection(Arc<str>),
It used to in an intermediate version of this, will change it back. I would like to eventually ditch the named lifetime altogether.

2024-10-07 17:16 UTC, xorgy commented on parley/src/layout/mod.rs
> +pub mod editor;
It is very closely tied to the layout, so I think it belongs at least in layout.

2024-10-07 17:56 UTC, xorgy commented on parley/src/lib.rs
>  pub use builder::{RangedBuilder, TreeBuilder};
That's a fair reason to have a bare re-export.

2024-10-07 18:18 UTC, xorgy commented on parley/src/layout/editor.rs
> +pub enum PlainEditorOp<'a, T>
I've added some basic doc comments for the public APIs.

2024-10-07 18:18 UTC, xorgy commented on parley/src/layout/editor.rs
> +pub struct PlainEditor<'a, T>
Added.

2024-10-07 18:19 UTC, xorgy commented on parley/src/layout/mod.rs
> +pub mod editor;
I've reexported `PlainEditor` and `PlainEditorOp` on Parley, I'm convinced by your argument for that.

2024-10-07 18:36 UTC, xorgy commented on parley/src/layout/editor.rs
> +    DeleteCurrentSelectionOrToPreviousWordBoundary,
I've made these operation names simpler.

2024-10-09 14:43 UTC, xorgy commented on parley/src/layout/editor.rs
> +    default_style: Arc<[StyleProperty<'a, T>]>,
Having reviewed the options for this, keeping things as they are is probably the right way to go. The next iteration ideally should make both the editor and the operations free of named lifetimes.

2024-10-09 15:11 UTC, nicoburns commented on parley/src/layout/editor.rs
> +    default_style: Arc<[StyleProperty<'a, T>]>,
@xorgy Have you made this work in Masonry? I feel like this API is likely to be unusable for setting styles that contain lifetimes (without either leaking or hardcoding them (so they have a `'static` lifetime)). My suggestion in the short term would be create duplicate "owned" variants of `StyleProperty` (and sub-structs).

2024-10-09 15:11 UTC, nicoburns approved these changes
I still have concerns around the styling API, but happy for those to be addressed in a follow up (or to be shown why they are not a problem in practice).

2024-10-09 15:21 UTC, raphlinus commented on examples/vello_editor/src/main.rs
> +    print!("{}", app.editor.text());
Was it intended to leave this in?

2024-10-09 15:49 UTC, merged

2024-10-16 13:24 UTC, DJMcNab commented on parley/src/layout/editor.rs
> +        t: impl IntoIterator<Item = PlainEditorOp<'a, T>>,
I see. I don't think we can possibly avoid doing this, so I think this is the right API. 
Some operations could be applied immediately, but it's unclear if that's worthwhile.

2024-10-16 13:45 UTC, xorgy commented on parley/src/layout/editor.rs
> +        t: impl IntoIterator<Item = PlainEditorOp<'a, T>>,
I think that invalidation is the correct final form, but operations were an expedient way to do this. Taking configuration (style, width, and scale) out of the operation set is probably a good first move. PlainEditor should probably be constructed with an owned default style, a width, and a scale; and then each of these should be mutable with a method.

2024-10-16 13:45 UTC, xorgy commented on parley/src/layout/editor.rs
> +                    layout_after = true;
Becomes invalid, it's a bug.